# Generated by Django 2.1.5 on 2019-02-10 03:29

from django.db import migrations, models
import django.utils.timezone
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, help_text='Text to describe the Newsletter')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.BooleanField(default=False)),
                ('html', django_grapesjs.models.fields.GrapesJsHtmlField()),
            ],
        ),
    ]
