# Generated by Django 2.0.13 on 2019-03-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='plain_text',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
