# Generated by Django 2.1.5 on 2019-02-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_newsletterindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='sent',
        ),
    ]
