# Generated by Django 2.1.5 on 2019-02-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_remove_newsletter_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
