# Generated by Django 2.1.5 on 2019-02-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycategory',
            name='id',
        ),
        migrations.AddField(
            model_name='storycategory',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
