# Generated by Django 2.1.5 on 2019-02-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20190203_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='categories',
        ),
    ]
