# Generated by Django 2.1.5 on 2019-01-22 04:58

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20190122_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='stories', to='base.StoryCategory'),
        ),
    ]
