# Generated by Django 2.0.13 on 2019-03-13 04:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20190312_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='icon',
        ),
        migrations.AddField(
            model_name='issue',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 13, 4, 34, 46, 228458, tzinfo=utc), verbose_name='Date article published'),
            preserve_default=False,
        ),
    ]
