# Generated by Django 2.1.5 on 2019-02-26 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_remove_storypage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='date_published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date article published'),
            preserve_default=False,
        ),
    ]
