# Generated by Django 2.1.5 on 2019-02-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionpage',
            name='body',
        ),
    ]
