# Generated by Django 2.1.5 on 2019-02-26 03:44

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submissionpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionpage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='submissionpage',
            name='subheader',
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='body_text',
            field=wagtail.core.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
