# Generated by Django 2.0.13 on 2019-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
