# Generated by Django 2.0.13 on 2019-03-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='left_title',
            new_name='left_title_bottom',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='right_title',
            new_name='left_title_top',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='right_title_bottom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='right_title_top',
            field=models.TextField(blank=True),
        ),
    ]
