# Generated by Django 2.0.13 on 2019-03-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20190304_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='bio_title',
            new_name='bio_title_bottom',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='bio_title_top',
            field=models.TextField(blank=True),
        ),
    ]
