# Generated by Django 2.0.13 on 2019-03-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20190304_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Embed Url'),
        ),
    ]
