# Generated by Django 2.1.5 on 2019-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='job_title',
        ),
        migrations.AddField(
            model_name='author',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Facebook Handle'),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Instagram Handle'),
        ),
        migrations.AddField(
            model_name='author',
            name='introduction',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Author Introduction'),
        ),
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Twitter Handle'),
        ),
    ]
