# Generated by Django 2.1.5 on 2019-01-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190114_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycategory',
            name='icon',
        ),
    ]
